version: "3.8"

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '6000:80'
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - .:/var/www/html:delegated
    # ports:
    #   - '3000:9000'
 
      
  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7
    ports:
      - '3305:3306'
    env_file:
      - ./env/mysql.env

  doctrine:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile 
    volumes:
      - .:/var/www/html
    entrypoint: ["php", "/var/www/html/vendor/bin/doctrine"]
  # npm:
