<?php
$this->headLink()
    ->prependStylesheet('https://use.fontawesome.com/releases/v5.13.0/css/all.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css');
$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-3.5.1.min.js');
?>
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    
    <?= $this->headTitle('IMAPP')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink(array(
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => '/img/favicon.ico'
    ))->prependStylesheet("/admin/dist/css/adminlte.min.css")
        ->prependStylesheet("/admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css")
        ->prependStylesheet("/admin/plugins/fontawesome-free/css/all.min.css") ?>
    <?= $this->headScript()
        ->prependFile("/admin/dist/js/adminlte.min.js")
        ->prependFile("/admin/plugins/bootstrap/js/bootstrap.bundle.min.js")
        ->prependFile("/admin/plugins/jquery/jquery.min.js");
    ?>
</head>

<body class="hold-transition login-page">



    <?= $this->content ?>




    <?= $this->inlineScript() ?>
</body>

</html>