<?php $userForm = $form->get("userFieldset"); ?>
<div class="input-group mb-3">
    <?php
    $element = $userForm->get('username');
    //  echo $this->formlabel($element);
    ?>
    <?php
    echo $this->formElement($element);
    ?>
    <div class="input-group-append">
        <div class="input-group-text">
            <span class="fas fa-user"></span>
        </div>
    </div>
    <div class="col-12"  style="font-size: 9px; color: red;">
        <?php
        echo $this->formElementErrors($element);
        ?>
    </div>
</div>
<div class="input-group mb-3">
    <?php
    $element = $userForm->get('email');
    echo $this->formElement($element);
    ?>
    <div class="input-group-append">
        <div class="input-group-text">
            <span class="fas fa-envelope"></span>
        </div>
    </div>
    <div class="col-12"  style="font-size: 9px; color: red;">
        <?php
        echo $this->formElementErrors($element);
        ?>
    </div>
</div>
<div class="input-group mb-3">
    <?php
    $element = $userForm->get('password');
    echo $this->formElement($element);
    ?>
    <div class="input-group-append">
        <div class="input-group-text">
            <span class="fas fa-lock"></span>
        </div>
    </div>
    <div class="col-12"  style="font-size: 9px; color: red;">
        <?php
        echo $this->formElementErrors($element);
        ?>
    </div>
</div>
<div class="input-group mb-3">
    <?php
    $element = $userForm->get('passwordVerify');
    echo $this->formElement($element);
    ?>
    <div class="input-group-append">
        <div class="input-group-text">
            <span class="fas fa-lock"></span>
        </div>
    </div>
    <div class="col-12" style="font-size: 9px; color: red;">
        <?php
        echo $this->formElementErrors($element);
        ?>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="icheck-primary">
            <!-- <input type="checkbox" id="agreeTerms" name="terms" value="agree"> -->
            <?php
            $element = $userForm->get("terms");
            echo $this->formCheckbox($element);
            ?>
            <label for="agreeTerms">
                I agree to the <a href="#">terms</a>
            </label>
        </div>
    </div>
    <!-- /.col -->
    <div class="col-12">
        <?php echo  $this->formSubmit($form->get('submit')) ?>
    </div>
    <!-- /.col -->
</div>