<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="https://getlaminas.org/images/favicon/favicon.ico" />
    <?= $this->headTitle('IMAPP')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink(array(
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => '/img/favicon.ico'
    ))->prependStylesheet("/css/custom.css")
    ?>
    <?= $this->headScript()
        ->prependFile("https://unpkg.com/sweetalert/dist/sweetalert.min.js")
        ->prependFile("https://cdn.jsdelivr.net/npm/vue-toast-notification@0.6.2/dist/index.min.js")
        ->prependFile("https://cdn.jsdelivr.net/npm/vue@2.6.11")
        ->prependFile("https://cdnjs.cloudflare.com/ajax/libs/axios/0.27.2/axios.min.js")

        ->prependFile("/admin/plugins/jquery/jquery.min.js");
    ?>

</head>

<body>

    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 hero">
                    <h1>Local, organic, artisan, handmade goods.</h1>
                </div>
            </div>
        </div>
    </header>

    <!-- Page Content -->
    <div class="container">

        <div class="row">
            <div class="col-xs-12 col-sm-8">
                <h2>What We Do</h2>
                <p></p>Church-key portland authentic unicorn, pickled try-hard venmo gochujang prism you probably haven't heard of them. Green juice brunch seitan, PBR&B franzen portland microdosing art party wolf tofu 8-bit letterpress gastropub kogi.</p>
                <p></p>Bitters artisan ugh, raclette waistcoat four loko semiotics fanny pack before they sold out snackwave four dollar toast vexillologist.</p>
                <p><button class="button">Contact Us</button></p>
            </div>
            <div class="col-xs-12 col-md-4">
                <h2>Contact Us</h2>
                <div>
                    <strong>Branch & Oak</strong>
                    <br />48151 Pine Road
                    <br />Portland, OR 62342
                    <br />
                    <br />
                </div>
                <div>
                    <abbr title="Phone">P: </abbr>(123) 456-7890
                    <br />
                    <abbr title="Email">E: </abbr> <a href="mailto:#">Email Us</a>
                </div>
            </div>
        </div>

        <!-- /.row -->

        <hr>

        <div class="row text-center">

            <div class="col-xs-12">
                <h1>What we offer</h1>
                <br />
            </div>

            <div class="col-xs-12 col-md-4">
                <img class="image image--circle image--center" src="https://source.unsplash.com/1w1OMV8CEeM/300x300" alt="">
                <h2>Bespoke</h2>
                <p>La croix vaporware viral vexillologist, flannel jianbing you probably haven't heard of them lomo selfies fixie banjo bespoke literally.</p>
            </div>
            <div class="col-xs-12 col-md-4">
                <img class="image image--circle image--center" src="https://source.unsplash.com/MMtVD2ew1BA/300x300" alt="">
                <h2>Gluten-Free</h2>
                <p>Literally tacos tumeric heirloom fingerstache banjo green juice fashion axe locavore, freegan woke kogi vice photo booth.</p>
            </div>
            <div class="col-xs-12 col-md-4">
                <img class="image image--circle image--center" src="https://source.unsplash.com/SK1_JK-ZHOo/300x300" alt="">
                <h2>Farm to Table</h2>
                <p>Helvetica pop-up raw denim, lomo godard tbh synth jean shorts. Aesthetic tumblr coloring book taco tofu.</p>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <?= $this->content ?>


    </div>
    <!-- /.container -->

    <footer class="footer" />

   


</body>

</html>