<div class="login-box">
    <?php if ($flashes = $this->flash()) : ?>
        <ul>
            <?php foreach ($flashes as $key => $message) : ?>
                <div class="alert alert-<?= $key ?> alert-dismissable fade show" role="alert">
                    <?php echo $message; ?>
                    <button class="close" type="button" data-dismiss="alert" aria-label=""></button>
                </div>

            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <div class="login-logo">

    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">You forgot your password? Here you can easily retrieve a new password.</p>

            <form action="<?= $this->url("authentication.forgot.password") ?>" method="post">
                <div class="input-group mb-3">
                    <input type="email" class="form-control" name="forgotpassword" id="forgotpassword" placeholder="Email">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary btn-block">Request new password</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <p class="mt-3 mb-1">
                <a href="<?= $this->url("authentication.login") ?>">Login</a>
            </p>
            <p class="mb-0">
                <a href="<?= $this->url("authentication.create.user") ?>" class="text-center">Register a new membership</a>
            </p>
        </div>
        <!-- /.login-card-body -->
    </div>
</div>