<div class="lockscreen-wrapper">
    <div class="lockscreen-logo">
        <!-- <a href="../../index2.html"><b>Admin</b>LTE</a> -->
      <img height=100 src="https://www.svgrepo.com/show/178334/padlock-lock.svg">
    </div>
    <!-- User name -->
    <!-- <div class="lockscreen-name">John Doe</div> -->

    <!-- START LOCK SCREEN ITEM -->
    <div class="lockscreen-item">
        <!-- lockscreen image -->
        <!-- <div class="lockscreen-image">
            <img src="../../dist/img/user1-128x128.jpg" alt="User Image">
        </div> -->
        <!-- /.lockscreen-image -->

        <!-- lockscreen credentials (contains the form) -->
        <form class="lockscreen-credentials">
            <div class="input-group">
                <input type="email" class="form-control" placeholder="Email">

                <div class="input-group-append">
                    <button type="button" class="btn">
                   
                        <i class="fas fa-arrow-right text-muted"></i>
                    </button>
                </div>
            </div>
        </form>
        <!-- /.lockscreen credentials -->

    </div>
    <!-- /.lockscreen-item -->
    <div class="help-block text-center">
       Enter your email to get reason for deactivation
    </div>
    <div class="text-center">
        <a href="<?= $this->url("authentication.login") ?>">Or sign in as a different user</a>
    </div>
    
</div>