<?php
echo $this->headTitle("Login");
echo $this->headmeta("Login Page ");
?>
<div class="login-box">
  <?php if (isset($error)) : ?>
    <div class="alert alert-danger" role="alert">
      <?= $this->escapeHtml($error) ?>
    </div>
  <?php endif ?>
  <?php if ($flashes = $this->flash()) : ?>
      <ul>
        <?php foreach ($flashes as $key => $message) : ?>
          <div class="alert alert-<?= $key ?> alert-dismissable fade show" role="alert">
            <?php echo $message; ?>
            <button class="close" type="button" data-dismiss="alert" aria-label=""></button>
          </div>

        <?php endforeach; ?>
      </ul>
    <?php endif; ?>

  <div class="login-logo">
    <a href=""><b> Logo Here</b></a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    
    <div class="card-body login-card-body">
      <p class="login-box-msg">Welcome to </p>

      <form autocomplete="off" action="<?= $this->url("authentication.login") ?>" method="post">
        <div class="input-group mb-3">
          <input type="text" class="form-control" required name="username" id="username" placeholder="Email or Phone Number">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" name="password" required id="password" class="form-control" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <input type="submit" value="Sign In" class="btn btn-primary btn-block" name="submit">
            <!-- <button type="submit" class="">Sign In</button> -->
          </div>
          <!-- /.col -->
        </div>
      </form>

      <div class="social-auth-links text-center mb-3">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
        </a>
      </div>
      <!-- /.social-auth-links -->

      <p class="mb-1">
        <a href="<?= $this->url("authentication.forgot.password")?>">I forgot my password</a>
      </p>
      <p class="mb-0">
        <a href="<?= $this->url("authentication.create.user") ?>" class="text-center">Register a new membership</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->