<?php
echo $this->headTitle("Successful registration");
// echo $this->headmeta("Login Page ");
?>
<div class="login-box">
    <!-- /.login-logo -->
    <div class="card">
    <div class="alert alert-success alert-dismissible">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <h5><i class="icon fas fa-check"></i> Successfull Registration</h5>
                  Successfully registered,a link has been sent to your email please confirm the your email 
                </div>
        <a href="<?= $this->url("authentication.login")?>" class="btn btn-success btn-block">Login </a>
        <!-- /.login-card-body -->
    </div>
</div>
<!-- /.login-box -->