<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            Authentication\Handler\CreateUserApiHandler::class => Authentication\Handler\CreateUserApiHandlerFactory::class,
            Authentication\Handler\CreateUserHandler::class => Authentication\Handler\CreateUserHandlerFactory::class,
            Authentication\Handler\LoginApiHandler::class => Authentication\Handler\LoginApiHandlerFactory::class,
            Authentication\Handler\LoginHandler::class => Authentication\Handler\LoginHandlerFactory::class,
            Authentication\Middleware\AuthenticationMiddleware::class => Authentication\Middleware\AuthenticationMiddlewareFactory::class,
            Customer\Handler\DashboardAPIHandler::class => Customer\Handler\DashboardAPIHandlerFactory::class,
            Customer\Handler\DashboardHandler::class => Customer\Handler\DashboardHandlerFactory::class,
        ],
    ],
];
