<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            Authentication\Handler\CreateUserApiHandler::class => Authentication\Handler\CreateUserApiHandlerFactory::class,
            Authentication\Handler\CreateUserHandler::class => Authentication\Handler\CreateUserHandlerFactory::class,
            Authentication\Handler\LoginApiHandler::class => Authentication\Handler\LoginApiHandlerFactory::class,
            Authentication\Handler\LoginHandler::class => Authentication\Handler\LoginHandlerFactory::class,
            Authentication\Middleware\AuthenticationMiddleware::class => Authentication\Middleware\AuthenticationMiddlewareFactory::class,
            Customer\Handler\DashboardAPIHandler::class => Customer\Handler\DashboardAPIHandlerFactory::class,
            Customer\Handler\DashboardHandler::class => Customer\Handler\DashboardHandlerFactory::class,
            Training\Handler\ActivateCourseCountHandler::class => Training\Handler\ActivateCourseCountHandlerFactory::class,
            Training\Handler\ActivateTrainingRewardHandler::class => Training\Handler\ActivateTrainingRewardHandlerFactory::class,
            Training\Handler\AggregateRewardHandler::class => Training\Handler\AggregateRewardHandlerFactory::class,
            Training\Handler\CountInProgressTrainingHandler::class => Training\Handler\CountInProgressTrainingHandlerFactory::class,
            Training\Handler\CountTotalCourseHandler::class => Training\Handler\CountTotalCourseHandlerFactory::class,
            Training\Handler\CountTotalProgramemHandler::class => Training\Handler\CountTotalProgramemHandlerFactory::class,
            Training\Handler\CountTotalTrainingHandler::class => Training\Handler\CountTotalTrainingHandlerFactory::class,
            Training\Handler\EnrollHandler::class => Training\Handler\EnrollHandlerFactory::class,
            Training\Handler\EnrollsHandler::class => Training\Handler\EnrollsHandlerFactory::class,
            Training\Handler\GetAllPublishedTrainingHandler::class => Training\Handler\GetAllPublishedTrainingHandlerFactory::class,
            Training\Handler\GetAllTrainingHandler::class => Training\Handler\GetAllTrainingHandlerFactory::class,
            Training\Handler\GetCourseHandler::class => Training\Handler\GetCourseHandlerFactory::class,
            Training\Handler\GetProgrammesHandler::class => Training\Handler\GetProgrammesHandlerFactory::class,
            Training\Handler\GetUserTrainingSubmitStatusHandler::class => Training\Handler\GetUserTrainingSubmitStatusHandlerFactory::class,
            Training\Handler\PostAssignmentHandler::class => Training\Handler\PostAssignmentHandlerFactory::class,
            Training\Handler\RoomCourseActivityHandler::class => Training\Handler\RoomCourseActivityHandlerFactory::class,
            Training\Handler\RoomHandler::class => Training\Handler\RoomHandlerFactory::class,
            Training\Handler\ShowAssignmentResponseViewHandler::class => Training\Handler\ShowAssignmentResponseViewHandlerFactory::class,
            Training\Handler\SimilarTrainingHandler::class => Training\Handler\SimilarTrainingHandlerFactory::class,
            Training\Handler\SubmitAssignmentStatusHandler::class => Training\Handler\SubmitAssignmentStatusHandlerFactory::class,
            Training\Handler\SubmitUserTrainingHandler::class => Training\Handler\SubmitUserTrainingHandlerFactory::class,
            Training\Handler\TakenCoursesHandler::class => Training\Handler\TakenCoursesHandlerFactory::class,
            Training\Handler\TrainingAllHandler::class => Training\Handler\TrainingAllHandlerFactory::class,
            Training\Handler\TrainingIndexHandler::class => Training\Handler\TrainingIndexHandlerFactory::class,
            Training\Handler\TrainingRewardHandler::class => Training\Handler\TrainingRewardHandlerFactory::class,
            Training\Handler\TrainingViewHandler::class => Training\Handler\TrainingViewHandlerFactory::class,
            Training\Handler\UserTrainingHandler::class => Training\Handler\UserTrainingHandlerFactory::class,
            Training\Handler\ViewMilestoneResourceHandler::class => Training\Handler\ViewMilestoneResourceHandlerFactory::class,
            Training\Service\ClassRoomService::class => Training\Service\ClassRoomServiceFactory::class,
            Training\Service\CourseService::class => Training\Service\CourseServiceFactory::class,
            Training\Service\ProgrammesService::class => Training\Service\ProgrammesServiceFactory::class,
            Training\Service\TrainingService::class => Training\Service\TrainingServiceFactory::class,
            Training\Service\YoutubeApiService::class => Training\Service\YoutubeApiServiceFactory::class,
            Women\HandlerShowEventFormHandler::class => Women\HandlerShowEventFormHandlerFactory::class,
            Women\Handler\CreateEventHandler::class => Women\Handler\CreateEventHandlerFactory::class,
            Women\Handler\CreateStoryHandler::class => Women\Handler\CreateStoryHandlerFactory::class,
            Women\Handler\EditProfileHandler::class => Women\Handler\EditProfileHandlerFactory::class,
            Women\Handler\NetworkHandler::class => Women\Handler\NetworkHandlerFactory::class,
            Women\Handler\ProfileHandler::class => Women\Handler\ProfileHandlerFactory::class,
            Women\Handler\ReadStoryHandler::class => Women\Handler\ReadStoryHandlerFactory::class,
            Women\Handler\RegisterForEventHandler::class => Women\Handler\RegisterForEventHandlerFactory::class,
            Women\Handler\ShowEventFormHandler::class => Women\Handler\ShowEventFormHandlerFactory::class,
            Women\Handler\ShowProfileFormHandler::class => Women\Handler\ShowProfileFormHandlerFactory::class,
            Women\Handler\ShowStoryFormHandler::class => Women\Handler\ShowStoryFormHandlerFactory::class,
            Women\Handler\StoryHandler::class => Women\Handler\StoryHandlerFactory::class,
            Women\Handler\ViewEventHandler::class => Women\Handler\ViewEventHandlerFactory::class,
        ],
    ],
];
